name: Create ISO image for guix

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install Guix
        run: |
          wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh
          chmod +x guix-install.sh
          yes | sudo ./guix-install.sh
          #sudo apt install guix

      - name: Build
        run: |
          guix time-machine -C './channels.scm' -- describe -f channels > './channels_.scm'
          #building image
          image=$(guix time-machine -C './channels_.scm' -- system image -t iso9660 './installer.scm')
          
          export RELEASE_TAG=$(date +"%Y%m%d%H%M")
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          cp $image ./guix-installer-$RELEASE_TAG.iso

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Guix Image - ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          files: guix-installer-${{ env.RELEASE_TAG }}.iso
